import type { SiteContent } from './types';

export const DEFAULT_SITE_CONTENT: SiteContent = {
  settings: {
    companyName: 'Reel OPS Media',
    navLinks: [
      { label: 'Projects', href: '#projects' },
      { label: 'Brand', href: '#team' },
      { label: 'FAQ', href: '#services' },
      { label: 'Demo', href: '#contact' },
    ],
    contactLabel: 'Contact',
    contactHref: '#contact',
    footerHoursLabel: 'Operation Hours',
    footerHoursValue: 'Monday to Friday',
    footerTagline: 'Be the reason you stand out. Get a leg up in your space.',
    instagramUrl: 'https://instagram.com/reelopsmedia',
    linkedinUrl: 'https://linkedin.com/company/reelopsmedia',
    developerName: 'Desgnmate.com',
    developerUrl: 'https://desgnmate.com',
  },
  hero: {
    eyebrow: 'Reel OPS Media',
    titleLine1: 'Next Level',
    titleLine2: 'Content',
    subtitle:
      'Driving real business growth through strategic video and media marketing. We turn your vision into content that converts.',
    primaryCtaLabel: 'View Projects',
    primaryCtaHref: '#projects',
    secondaryCtaLabel: 'Book A Demo',
    secondaryCtaHref: '#contact',
    backgroundVideo: '/videos/hero-bg.mp4',
  },
  mission: {
    leftLine1: 'OUR',
    leftLine2: 'MISSION',
    rightLine1: 'YOUR',
    rightLine2: 'SUCCESS',
  },
  servicesLabel: 'Services',
  servicesTitle: 'What We Do',
  services: [
    { title: 'Meet And Greet', description: 'Book a call and lets discuss your idea.' },
    { title: 'Strategy Session', description: 'Book a call and lets discuss your idea.' },
    { title: 'Content Creation', description: 'Book a call and lets discuss your idea.' },
    { title: 'Analyses', description: 'Book a call and lets discuss your idea.' },
  ],
  servicesCtaLabel: 'See Packages',
  servicesPastProjectsLabel: 'See Past Projects Below',
  projectsLabel: 'Past Projects',
  projectsTitle: 'Our Work',
  projects: [
    {
      number: '01',
      image: '/images/project-01.jpg',
      imageAlt: 'Tactical Gear Co. project',
      video: '/images/project-01.mp4',
      tags: ['Brand Awareness', 'Social Media', 'Video Production'],
      name: 'Tactical Gear Co.',
      type: 'Brand Awareness Campaign',
      stats: [
        { label: 'Views', value: '1.8M' },
        { label: 'Engagement', value: '+310%', positive: true },
      ],
    },
    {
      number: '02',
      image: '/images/project-02.jpg',
      imageAlt: 'Tier 1 Athletics project',
      video: '/images/project-02.mp4',
      tags: ['Paid Ads', 'Content Strategy', 'Social Media'],
      name: 'Tier 1 Athletics',
      type: 'Content Campaign',
      stats: [
        { label: 'Views', value: '2.1M' },
        { label: 'Engagement', value: '+400%', positive: true },
        { label: 'Revenue', value: '+487%', positive: true },
      ],
    },
    {
      number: '03',
      image: '/images/project-03.jpg',
      imageAlt: 'Vanguard Fitness project',
      video: '/images/project-03.mp4',
      tags: ['Product Launch', 'Video Production', 'Paid Ads'],
      name: 'Vanguard Fitness',
      type: 'Product Launch',
      stats: [
        { label: 'Reach', value: '950K' },
        { label: 'Conversions', value: '+220%', positive: true },
      ],
    },
    {
      number: '04',
      image: '/images/project-04.jpg',
      imageAlt: 'Desert Storm LLC project',
      video: '/images/project-04.mp4',
      tags: ['Brand Identity', 'Commercial', 'Video Production'],
      name: 'Desert Storm LLC',
      type: 'Brand Identity',
      stats: [{ label: 'Views', value: '1.5M' }, { label: 'Growth', value: '+320%', positive: true }],
    },
    {
      number: '05',
      image: '/images/project-05.jpg',
      imageAlt: 'Iron Republic project',
      video: '/images/project-05.mp4',
      tags: ['Social Media', 'Content Creation', 'Photography'],
      name: 'Iron Republic',
      type: 'Social Campaign',
      stats: [{ label: 'Followers', value: '+12K' }, { label: 'Engagement', value: '+180%', positive: true }],
    },
    {
      number: '06',
      image: '/images/project-06.jpg',
      imageAlt: 'Apex Dynamics project',
      video: '/images/project-06.mp4',
      tags: ['Brand Awareness', 'Paid Ads', 'Analytics'],
      name: 'Apex Dynamics',
      type: 'Full Service',
      stats: [{ label: 'Reach', value: '3.2M' }, { label: 'ROI', value: '+550%', positive: true }],
    },
  ],
  teamLabel: 'Team',
  teamTitle: 'Our Workforce',
  team: {
    name: 'Isaac',
    role: 'Founder & CEO',
    image: '/images/ceo-v2.jpeg',
    imageAlt: 'CEO of Reel OPS Media',
    bio: "Isaac has been in the video space since 2019. He's been behind the lens for over 5 years and counting. He's produced, directed and filmed some of the most watched videos in Arizona. Whether it's your work done, or figure it out.",
    credentials: [
      { label: 'Code Name', value: 'Overlord' },
      { label: 'Specializes in', value: 'Brand Strategy' },
      { label: 'Company Affiliation', value: 'Reel OPS Media' },
      { label: 'Work Experience', value: '10+ Years' },
      { label: 'Operators', value: '15+ On Stand-By' },
      { label: "Coffee's Sipped", value: '10,563+' },
    ],
  },
  alliesLabel: 'Network',
  alliesTitle: 'Allies',
  alliesDescription:
    "We don't work alone. Our trusted network of partners and contractors ensures every project gets the specialized talent it needs.",
  allies: [
    { name: 'Tier 1', image: '/images/ally-tier1.jpg', imageAlt: 'Tier 1', role: 'Production Partner' },
    { name: 'Brus Media', image: '/images/ally-brus.jpg', imageAlt: 'Brus Media', role: 'Post-Production' },
    { name: 'Empire Rentals', image: '/images/ally-empire.jpg', imageAlt: 'Empire Rentals', role: 'Equipment & Gear' },
  ],
  contractorCount: 6,
  contractorTitle: 'Contractors',
  contractorSubtitle: 'On-call talent pool',
  contractors: [
    { role: 'Camera Operator', count: 2 },
    { role: 'Lighting Expert', count: 1 },
    { role: 'Audio Specialist', count: 1 },
    { role: 'Editor', count: 1 },
    { role: 'Drone Pilot', count: 1 },
  ],
  clientsLabel: 'Past Clients',
  clients: [
    'Tactical Gear Co.',
    'Tier 1 Athletics',
    'Brus Media',
    'Empire Rentals',
    'Vanguard Fitness',
    'Desert Storm LLC',
    'Iron Republic',
    'Apex Dynamics',
  ],
  contact: {
    title: "Let's Chat",
    subtitle: 'Find a time using Calendly below, answer some basic questions, and lets discuss your project',
    backgroundImage: '/images/book-a-call-bg.jpg',
    meetingName: 'Hamza Ehsan',
    meetingTitle: 'Discovery',
    duration: '30 min',
    conferencingText: 'Web conferencing details provided upon confirmation.',
    description: 'This meeting is for an introductory chat to discuss a potential project.',
    calendarMonth: 'November 2024',
    timezone: 'UK, Ireland, Lisbon Time (8:24am)',
  },
  testimonialsLabel: 'Testimonials',
  testimonialsTitle: 'Client Stories',
  testimonials: [
    { quote: 'Reel Ops Didn’t Just Deliver A Video; They Delivered A Weapon For Our Marketing Arsenal.', name: 'David Dimiglio', role: 'CEO', company: 'Precision Industries' },
    { quote: 'Working with Reel OPS was a game-changer. Our brand visibility skyrocketed within the first month of the campaign launch.', name: 'Sarah Mitchell', role: 'Marketing Director', company: 'Apex Dynamics' },
    { quote: 'The production quality is unmatched. Every frame was intentional, every cut was precise. They turned our vision into reality.', name: 'Marcus Chen', role: 'Founder', company: 'Iron Republic' },
    { quote: 'They don’t just make content—they build narratives that move people. Our engagement rate tripled after working with them.', name: 'Jessica Rivera', role: 'Brand Manager', company: 'Tier 1 Athletics' },
    { quote: 'From concept to delivery, Reel OPS operated with military precision. On time, on budget, and beyond expectations.', name: 'Ryan Torres', role: 'COO', company: 'Vanguard Fitness' },
  ],
  testimonialStats: [
    { value: '4.9/5', label: 'Client Rating' },
    { value: '100%', label: 'On-Time Delivery' },
    { value: '98%', label: 'Would Recommend' },
  ],
};
